### ISSUE TITLE
Remove dependency on execsync?

### ISSUE THREAD

**Issue by davidham** [iamcarrico/generator-poole#12]
When I run 'yo poole' I get this message:

```
module.js:338
    throw err;
    ^
Error: Cannot find module './build/Release/shell'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-poole/node_modules/execSync/index.js:30:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

This appears to be an error related to execSync. I don't know what execSync does, but apparently it used to be a separate module and now it's built into Node? Here's a similar issue from another project:

https://github.com/percyhanna/mincer-ruby-sass/issues/2

See also #11. Would removing this dependency solve the issue?

**Comment by meherranjan** [comment]
Facing the same problem. I was able to find a workaround from this though. 
https://github.com/mgutz/execSync/issues/38

**Comment by johnslipper** [comment]
Have had the same problem myself today, would be great to remove the dependancy as have had issues using nvm and going back to < 0.12.0 is not really an option for me.
